name: Build and deploy

#on:
#  push:
#    branches: [ k8s ]

on:
  #schedule:
  #  - cron: '19 16 * * *'
  push:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: buildpacks/github-actions/setup-pack@v4.4.2
        with:
          pack-version: 0.21.1
      
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
          cache: maven      
      
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy artifacts
        run: make build deploy
