name: Build and deploy

#on:
#  push:
#    branches: [ k8s ]

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: buildpacks/github-actions/setup-pack@v4.4.2
        with:
          pack-version: 0.21.1

      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
          cache: maven

      - name: Log in to the container registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Deploy artifacts
        run: make build deploy
