name: Build and deploy

#on:
#  push:
#    branches: [ k8s ]

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: buildpacks/github-actions/setup-pack@v4.4.2
        with:
          pack-version: 0.21.1
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
          cache: maven      
      - name: Deploy artifacts
        run: make build deploy
